#! /bin/sh

bspc config border_width        1
bspc config window_gap         3

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance  false 
bspc config focus_follows_pointer false

wmname LG3D

bspc monitor -d 1 2 3 4

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a bitwig-studio pseudo_tiled=on ignore_ewmh_focus=on desktop ^2
